"""add device credentials

Revision ID: 0948ab04465a
Revises: f530a9401cdb
Create Date: 2026-09-11 05:51:05.121807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0948ab04465a'
down_revision = 'f530a9401cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_credentials_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_credentials_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_credentials_token_hash'))

    op.drop_table('device_credentials')
    # ### end Alembic commands ###
